from dataclasses import dataclass
from .. import db


@dataclass
class srarun(db.Model):
    run = db.Column(db.Text, primary_key=True)
    release_date = db.Column(db.DateTime)
    tax_id = db.Column(db.Text)
    scientific_name = db.Column(db.Text)

    load_date = db.Column(db.DateTime)
    spots = db.Column(db.BigInteger)
    bases = db.Column(db.BigInteger)
    spots_with_mates = db.Column(db.BigInteger)
    avg_length = db.Column(db.BigInteger)
    size_mb = db.Column(db.BigInteger)
    assembly_name = db.Column(db.Text)
    download_path = db.Column(db.Text)
    experiment = db.Column(db.Text)
    library_name = db.Column(db.Text)
    library_strategy = db.Column(db.Text)
    library_selection = db.Column(db.Text)
    library_source = db.Column(db.Text)
    library_layout = db.Column(db.Text)
    insert_size = db.Column(db.BigInteger)
    insert_dev = db.Column(db.Float)
    platform = db.Column(db.Text)
    model = db.Column(db.Text)
    sra_study = db.Column(db.Text)
    bio_project = db.Column(db.Text)
    study_pubmed_id = db.Column(db.Text)
    project_id = db.Column(db.Text)
    sample = db.Column(db.Text)
    bio_sample = db.Column(db.Text)
    sample_type = db.Column(db.Text)
    tax_id = db.Column(db.Text)
    scientific_name = db.Column(db.Text)
    sample_name = db.Column(db.Text)
    g1k_pop_code = db.Column(db.Text)
    source = db.Column(db.Text)
    g1k_analysis_group = db.Column(db.Text)
    subject_id = db.Column(db.Text)
    sex = db.Column(db.Text)
    disease = db.Column(db.Text)
    tumor = db.Column(db.Text)
    affection_status = db.Column(db.Text)
    analyte_type = db.Column(db.Text)
    histological_type = db.Column(db.Text)
    body_site = db.Column(db.Text)
    center_name = db.Column(db.Text)
    submission = db.Column(db.Text)
    dbgap_study_accession = db.Column(db.Text)
    consent = db.Column(db.Text)
    run_hash = db.Column(db.Text)
    read_hash = db.Column(db.Text)
